version: '2.1'

services:
    db:
        image: mysql:5
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                http_proxy: ${PROXY}
                https_proxy: ${PROXY}
        volumes:
            - ${APP_PATH}:/var/www/docker
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: 
            context: nginx
            args:
                http_proxy: ${PROXY}
                https_proxy: ${PROXY}                
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
