version: '2.1'

services:
    db:
        image: mariadb:10.1
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                http_proxy: ${PROXY}
                https_proxy: ${PROXY}
                UID: ${UID}
        user: ${UID}
        volumes:
            - ${APP_PATH}:/var/www/docker
#            - ./logs/symfony:/var/www/docker/symfony/var/logs
    web:
        build: 
            context: nginx
            args:
                http_proxy: ${PROXY}
                https_proxy: ${PROXY}
                UID: ${UID}
        ports:
            - 8000:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
